yatube/about/urls.py
from django.urls import path
from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('about/', include('about.urls', namespace='about')),
]

handler403 = 'core.views.csrf_failure'
handler404 = 'core.views.page_not_found'
handler500 = 'core.views.internal_error'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/about/views.py
from django.views.generic.base import TemplateView


class AboutAuthorView(TemplateView):
    template_name = 'about/author.html'


class AboutTechView(TemplateView):
    template_name = 'about/tech.html'

yatube/templates/about/author.html
{% extends "base.html" %}
{% load static %}
{% block title %}Об авторе проекта{% endblock %}
{% block content %}
  <h1>Об авторе</h1>
  <p>
    <br>
    Привет! Меня зовут Евгений и я сейчас активно работаю над этим проектом. Изначальное его название -
    <b><span style="color:red">Ya</span>tube</b>, но временами бывает и <b><span style="color:red">Йа</span>туп</b>.
    Мне очень нравится, когда находится решение и проект возвращает изначальное название )
  </p>
  <p>
    <a href="{% url 'about:tech' %}" class="btn btn-primary">
      Задействованные технологии</a>
  </p>
  <p>
    Проект определенно будет дополняться, все изменения будут доступны тут
    <a class="git_logo" href="https://github.com/nicsea/">
      <img src="{% static 'img/github.png' %}" width="30" height="30" alt="GitHub">
    </a>
  </p>
{% endblock %}

yatube/templates/about/tech.html
{% extends "base.html" %}
{% load static %}
{% block title %}Технологии{% endblock %}
{% block content %}
  <div class="row">
    <h1>Технологии, которые используются в проекте</h1>
    <aside class="col-12 col-md-3">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          <img src="{% static 'img/python.png' %}" width="30" height="30" class="d-inline-block align-top"
               alt=""> Python
        </li>
        <li class="list-group-item">
          <img src="{% static 'img/django.png' %}" width="40" height="40" class="d-inline-block align-top"
               alt=""> Django
        </li>
        <li class="list-group-item">
          <img src="{% static 'img/bootstrap.png' %}" width="35" height="30" class="d-inline-block align-top"
               alt=""> Bootstrap
        </li>
      </ul>
    </aside>
    <article class="col-12 col-md-9">
      <br>
      <p>В проекте <a href="{% url 'about:author' %}" class="link-primary">мной</a>
        используется Python, Bootstrap и, конечно же Django.</p>
      <p>Фреймворк Django серьезно упростил
        управление пользователями и взаимодействие с базой данных посредством ORM. Внешняя красота проекта - это
        HTML, CSS и JS фреймворк Bootstrap. А связывает это все и оживляет - Python.</p>
    </article>
  </div>
{% endblock %}